---
sudo: required

language: python
python: "2.7"

services:
  - docker

env:
  - ES_IMAGE="elasticsearch-oss:7.3.2" ES_TYPE="" ES_TEMPLATE="new-index-template.json"
  - ES_IMAGE="elasticsearch-oss:6.2.2" ES_TYPE="test_type" ES_TEMPLATE="new-index-template-ES-6.x.json"
  - ES_IMAGE="elasticsearch:5.6.8" ES_TYPE="test_type" ES_TEMPLATE="new-index-template-ES-6.x.json" ES_USER="elastic" ES_PASS="changeme"

script:
  - tests/run_tests
